name: identiflora
description: "The Identiflora app is a plant identification app for those knowledgable of flora."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.3
  permission_handler: ^12.0.1
  camera: ^0.11.3
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/homepage/