name: identiflora
description: "The Identiflora app is a plant identification app for those knowledgable of flora."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  camera: ^0.11.3
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.2.1
  tflite_flutter: ^0.12.1
  image: ^4.1.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/homepage/
    - assets/model/